### ISSUE TITLE
Akkad Mission Tree

### ISSUE THREAD

**Issue by BrunoEvangelista17** [DanielLS2000/MegaPortuvesalis-HEE#23]

**Comment by BrThomasT3** [comment]
Rascunho da arvore feito no [photoshop](https://drive.google.com/file/d/1mqvhv9Kh8JSmeOaOdDe_Qljie6eFfIgN/view?usp=sharing)

**Comment by BrThomasT3** [comment]
Missões projetadas no Paradox Node Editor [Akkad_Missions.txt](https://github.com/user-attachments/files/18172227/Akkad_Missions.txt)

**Comment by BrThomasT3** [comment]
Tag do Akkad alterada e missões colocadas de forma superficial no jogo.
Revisão de missões programada pois missão monopolizar o golfo precisa de mais requisitos.
![Image](https://github.com/user-attachments/assets/cab7d597-d0ed-4f23-8688-c814939072b4)
![Image](https://github.com/user-attachments/assets/f507047e-dc8d-4751-b642-27fd64ec15ec)

**Comment by BrThomasT3** [comment]
Mais um Push feito com a arvore 95% pronta, apenas restando algumas localizações

**Comment by BrThomasT3** [comment]
Missões 100% prontas
